#import "../../template.typ": problem, deliverable

#problem("generate", "Generate text", "1 point")[
Using your decoder and your trained checkpoint, report the text generated by your model. You may need to manipulate decoder parameters, `temperature`, `top-p`, and so on, to get fluent outputs.

#deliverable[Text dump of at least `256` tokens of text, or until the first `<|endoftext|>` token, and a brief comment on the fluency of this output and at least two factors which affect how good or bad this output is.]
]
